# docker-compose.yml
services:

  model-app-serv:
    image: "ghcr.io/remla23-team15/app:latest"
    ports:
      - 8081:80
    depends_on:
      - model-service-serv
    environment:
      - MY_APP_URL=/predict
      - MY_APP_FEEDBACK=/feedback
      - BACKEND_HOST=model-service-serv:8080

  model-service-serv:
    image: "ghcr.io/remla23-team15/model-service:latest"
    ports:
      - 8080:8080
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - model-service-serv
      - model-app-serv
  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./monitoring/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./monitoring/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - 3000:3000
    depends_on:
      - prometheus
