# docker-compose.yml
services:

  model-app-serv:
    image: "ghcr.io/remla23-team15/app:latest"
    ports:
      - 8081:80
    depends_on:
      - model-service-serv
    environment:
      - MY_APP_URL=/predict
      - MY_APP_FEEDBACK=/feedback
      - BACKEND_HOST=model-service-serv:8080

  model-service-serv:
    image: "ghcr.io/remla23-team15/model-service:latest"
    ports:
      - 8080:8080
