# docker-compose.yml
services:

  model-app-serv:
    image: "ghcr.io/remla23-team15/app:latest"
    ports:
      - 8081:80
    depends_on:
      - model-service-serv

  model-service-serv:
    image: "ghcr.io/remla23-team15/model-service:latest"
    ports:
      - 8080:8080
