{
 "title": "Restaurants Reviews Sentiment",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model Accuracy",
   "type": "timeseries",
   "description": "Model accuracy of predictions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total requests amount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "total_predictions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Predictions Duration",
   "type": "timeseries",
   "description": "Duration of predictions in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "prediction_duration", "legendFormat": "__auto" }
   ]
  }
 ]
}