apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "model_app.fullname" . }}-{{ .Values.app_ingress.name }}
  labels:
    {{- include "model_app.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "model_app.fullname" . }}-{{ .Values.model_app_serv.name }}
      port:
        number: {{ .Values.model_app_serv.port }}