apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.model_app_depl.name }}
  labels:
    app: {{ .Values.model_app_depl.app }}
    {{- include "model_app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.model_app_depl.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.model_app_depl.name }}
      {{- include "model_app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.model_app_depl.app }}
        {{- include "model_app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.model_app_depl.container }}
        image: {{ .Values.model_app_depl.image }}:{{ .Values.model_app_depl.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.model_app_depl.port }}
        env:
          - name: MY_APP_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app_config.name }}
                key: model.path