apiVersion: v1
kind: Service
metadata:
  {{- $dot := . }}
  {{- with .Values.model_app_serv }}
  name: {{ include "model_app.fullname" $dot }}-{{ .name }}
  labels:
    app: {{ include "model_app.fullname" $dot }}-{{ .name }}
    {{- include "model_app.labels" $dot | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "model_app.fullname" $dot }}-{{ .app }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}