apiVersion: v1
kind: Service
metadata:
  {{- $dot := . }}
  {{- with .Values.model_service_serv }}
  name: {{ include "model_app.fullname" . }}-{{ .name }}
  labels:
    {{- include "model_app.labels" $dot | nindent 4 }}
spec:
  selector:
    app: {{ include "model_app.fullname" $dot }}-{{ .app }}
  ports:
  - protocol: TCP
    port: {{ .port }}
    targetPort: http
  {{- end }}