apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $dot := . }}
  {{- $c_name := .Values.app_config.name }}
  {{- with .Values.model_app_depl }}
  name: {{ include "model_app.fullname" $dot }}-{{ .name }}
  labels:
    app: {{ include "model_app.fullname" $dot }}-{{ .app }}
    {{- include "model_app.labels" $dot | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ include "model_app.fullname" $dot }}-{{ .app }}
      {{- include "model_app.selectorLabels" $dot | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "model_app.fullname" $dot }}-{{ .app }}
        {{- include "model_app.selectorLabels" $dot | nindent 8 }}
    spec:
      containers:
      - name: {{ include "model_app.fullname" $dot }}-{{ .container }}
        image: {{ .image }}:{{ .version }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .port }}
  {{- end }}
        env:
          - name: MY_APP_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "model_app.fullname" $dot }}-{{ $c_name }}
                key: model.path
          - name: MY_APP_FEEDBACK
            valueFrom:
              configMapKeyRef:
                name: {{ include "model_app.fullname" $dot }}-{{ $c_name }}
                key: model.feedback
          - name: BACKEND_HOST
          {{- with .Values.model_service_serv }}
            value: {{ include "model_app.fullname" $dot }}-{{ .name }}:{{ .port }}
          {{- end }}