apiVersion: v1
kind: Service
metadata:
  name: {{ include "model_app.fullname" . }}-{{ .Values.model_app_serv.name }}
  labels:
    app: {{ include "model_app.fullname" . }}-{{ .Values.model_app_serv.name }}
    {{- include "model_app.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "model_app.fullname" . }}-{{ .Values.model_app_serv.app }}
  ports:
    - port: {{ .Values.model_app_serv.port }}
      targetPort: {{ .Values.model_app_serv.targetPort }}