apiVersion: v1
kind: Service
metadata:
  name: {{ include "model_app.fullname" . }}-{{ .Values.model_service_serv.name }}
  labels:
    {{- include "model_app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "model_app.fullname" . }}-{{ .Values.model_service_serv.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.model_service_serv.port }}
    targetPort: http