apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $dot := . }}
  {{- with .Values.model_service_depl }}
  name: {{ include "model_app.fullname" $dot }}-{{ .name }}
  labels:
    app: {{ include "model_app.fullname" $dot }}-{{ .app }}
    {{- include "model_app.labels" $dot | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ include "model_app.fullname" $dot }}-{{ .app }}
      {{- include "model_app.selectorLabels" $dot | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "model_app.fullname" $dot }}-{{ .app }}
        {{- include "model_app.selectorLabels" $dot | nindent 8 }}
    spec:
      containers:
      - name: {{ include "model_app.fullname" $dot }}-{{ .container }}
        image: {{ .image }}:{{ .version }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
          - name: http
            containerPort: {{ .port }}
  {{- end }}