{{- if .Values.monitoring.active }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "model_app.fullname" . }}-{{ .Values.prometheus.name }}
  labels:
    release: {{ .Values.prometheus.release }}
spec:
  selector:
    matchLabels:
      app: {{ include "model_app.fullname" . }}-{{ .Values.model_app_serv.name }}
  endpoints:
  - interval: {{ .Values.prometheus.interval }}
{{- if .Values.monitoring.alerts }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "model_app.fullname" . }}-{{ .Values.prometheus.name }}-alerts
  labels:
    release: {{ .Values.prometheus.release }}
spec:
  groups:
    - name: {{ include "model_app.fullname" . }}-{{ .Values.prometheus.name }}-alerts
      rules:
        - alert: ModelAccuracyTooLow
          expr: (model_accuracy - model_accuracy offset 15m) < 0.4
          for: 5m
          labels:
            severity: Critical
{{- end }}
{{- end }}
